# Generated by Django 6.0.1 on 2026-04-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='user',
            new_name='student',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='selected_option',
            field=models.CharField(max_length=1),
        ),
    ]
